.\"
.\"  Original Copyright:
.\"  sl Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	car.1
.\"	@(#)sl.1
.\"
.TH CAR 1 "December 31, 2022"
.SH NAME
car \- cure your bad habit of mistyping
.SH SYNOPSIS
.B car
[
.B \-u
]
[
.I "file ..."
]
.SH DESCRIPTION
.B car
is a highly advanced animation program for curing your bad habit of mistyping.
.PP
.TP
.B \-u
(Ignored.)
.PP
.SH SEE ALSO
.BR cat (1)
.SH BUGS
It sometimes concatenate and print files.
.SH AUTHOR
KusaReMKN (https://github.com/KusaReMKN)
.PP
Original Version (SL):
Toyoda Masashi (mtoyoda@acm.org)
